# Generated by Django 4.0.3 on 2022-12-09 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_alter_serviceappt_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappt',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_name', to='service_rest.technician'),
        ),
        migrations.AlterField(
            model_name='serviceappt',
            name='vin',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
