# Generated by Django 4.0.3 on 2022-12-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_rename_vin_serviceappt_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='employee_num',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
